services:
  redis:
    networks:
      - redis-network

  postgres:
    networks:
      - postgres-network

  redis-insight:
    image: redislabs/redisinsight:3.6.0
    container_name: redis-insight
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDISINSIGHT_HOST: "0.0.0.0"
      REDISINSIGHT_ACCEPT_LICENCE: true
    ports:
      - "15540:5540"
    networks:
      - redis-network
    depends_on:
      redis:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
      POSTGRES_PASSWORD: "my-postgres-pass"
      POSTGRES_DB: identity-db
    ports:
      - "15432:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-network
  
  identity-svc:
    networks:
      - redis-network
      - postgres-network
    volumes:
      - .:/app

networks:
  redis-network:
    driver: bridge
  postgres-network:
    driver: bridge